os:
  - linux

language: php

php:
  - '7.1'

sudo: required

services:
  - docker

install: true

before_script:
  - docker pull tetraweb/php:7.1

before_script:
  - eval "$(ssh-agent)"
  - mkdir -p ~/.ssh
  - echo -e "$PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  
script:
  - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no deploy@shares.savaskartal.com
  - cd /var/www/vhosts/savaskartal.com/shares.savaskartal.com
  - php artisan down
  - git checkout
  - git pull
  - php artisan up
  - php artisan horizon:terminate
  - php artisan config:clear
  - php artisan view:clear
  - php artisan cache:clear
  - php artisan config:cache
