os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - eval "$(ssh-agent)"
  - mkdir -p /home/travis/.ssh
  - echo -e "$SSH_PRIVATE_KEY" > /home/travis/.ssh/id_rsa
  - chmod 600 /home/travis/.ssh/id_rsa
  - ssh-add /home/travis/.ssh/id_rsa
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /home/travis/.ssh/config'
  
script:
  - ssh deploy@bilisim1.eniyisite.net
  - cd /var/www/vhosts/savaskartal.com/shares.savaskartal.com
  - php artisan down
  - git checkout
  - git pull
  - php artisan up
  - php artisan horizon:terminate
  - php artisan config:clear
  - php artisan view:clear
  - php artisan cache:clear
  - php artisan config:cache
